import { Opportunity } from '@/types';

export const MOCK_OPPORTUNITIES: Opportunity[] = [
  {
    id: 'opp-1',
    title: 'AI/ML Engineering Intern',
    company: 'CognitiveLabs AI',
    companyLogo: '⚡',
    location: 'Bengaluru, KA (Hybrid)',
    type: 'Internship',
    stipend: '₹45,000 / month',
    duration: '6 Months',
    deadline: '2026-10-15',
    domain: 'Artificial Intelligence',
    requiredSkills: ['Python', 'Machine Learning', 'SQL', 'TensorFlow', 'REST APIs'],
    minimumCGPA: 8.0,
    eligibleBranches: ['Computer Science and Engineering', 'Information Technology', 'AI & Data Science'],
    description: 'Work alongside leading AI researchers building enterprise generative AI engines, fine-tuning LLMs, and building high-throughput machine learning pipelines.',
    responsibilities: [
      'Implement deep learning model architectures using PyTorch/TensorFlow.',
      'Process large-scale unstructured datasets with Pandas and SQL.',
      'Deploy inference microservices using FastAPI and REST API specs.',
      'Collaborate with product teams to evaluate model metrics.'
    ],
    perks: ['Pre-Placement Offer (PPO) Potential', 'Flexible Working Hours', 'Learning Allowance ($300)', 'Certificate of Internship']
  },
  {
    id: 'opp-2',
    title: 'Full Stack Web Developer Intern',
    company: 'NextGen Systems',
    companyLogo: '🚀',
    location: 'Remote',
    type: 'Remote Internship',
    stipend: '₹35,000 / month',
    duration: '3 Months',
    deadline: '2026-09-30',
    domain: 'Software Engineering',
    requiredSkills: ['React.js', 'TypeScript', 'Node.js', 'REST APIs', 'Git & GitHub'],
    minimumCGPA: 7.5,
    eligibleBranches: ['Computer Science and Engineering', 'Information Technology', 'Electronics & Comm'],
    description: 'Build modern SaaS web applications using Next.js, React, and Node.js microservices. Ideal for web developers passionate about clean UI and scalable backend logic.',
    responsibilities: [
      'Develop pixel-perfect UI components with Tailwind CSS & TypeScript.',
      'Integrate frontend applications with RESTful APIs.',
      'Write clean, modular unit tests and maintain Git repository hygiene.'
    ],
    perks: ['100% Remote Work', 'Mentorship from Senior Architects', 'Internship Certificate']
  },
  {
    id: 'opp-3',
    title: 'Data Analyst & Visualization Intern',
    company: 'AnalyticsScale Global',
    companyLogo: '📊',
    location: 'Gurugram, HR (Onsite)',
    type: 'Internship',
    stipend: '₹30,000 / month',
    duration: '6 Months',
    deadline: '2026-10-05',
    domain: 'Data Analytics',
    requiredSkills: ['SQL', 'Python', 'Data Visualization (PowerBI / Tableau)', 'Pandas & NumPy', 'Problem Solving'],
    minimumCGPA: 7.0,
    eligibleBranches: ['Computer Science and Engineering', 'Information Technology', 'Data Science', 'Electrical'],
    description: 'Transform complex business data into actionable executive dashboards. Perform statistical analysis and automate data ETL pipelines.',
    responsibilities: [
      'Design interactive PowerBI / Tableau dashboards for client insights.',
      'Write complex SQL queries and window functions for data mining.',
      'Prepare data insights reports for cross-functional management.'
    ],
    perks: ['Onsite Cafeteria', 'Industry Certification Coverage', 'PPO Track']
  },
  {
    id: 'opp-4',
    title: 'Cloud DevOps Associate',
    company: 'CloudSphere Technologies',
    companyLogo: '☁️',
    location: 'Hyderabad, TS (Hybrid)',
    type: 'Full-time',
    stipend: '₹12.5 LPA',
    duration: 'Full-time Role',
    deadline: '2026-10-20',
    domain: 'Cloud & Infrastructure',
    requiredSkills: ['Cloud Computing (AWS)', 'Docker', 'CI/CD Pipelines', 'Python', 'Linux & Networking'],
    minimumCGPA: 7.8,
    eligibleBranches: ['Computer Science and Engineering', 'Information Technology'],
    description: 'Manage automated deployment infrastructure, Kubernetes clusters, and AWS serverless architectures for enterprise web products.',
    responsibilities: [
      'Configure CI/CD pipelines using GitHub Actions.',
      'Containerize microservices using Docker & Kubernetes.',
      'Monitor cloud infrastructure uptime and cost efficiency.'
    ],
    perks: ['Health Insurance ₹5L', 'Annual Tech Bonus', 'Certifications Reimbursed']
  },
  {
    id: 'opp-5',
    title: 'Junior Cyber Security Analyst',
    company: 'Fortress Cyber Defense',
    companyLogo: '🛡️',
    location: 'Pune, MH (Onsite)',
    type: 'Full-time',
    stipend: '₹10.0 LPA',
    duration: 'Full-time Role',
    deadline: '2026-10-10',
    domain: 'Cybersecurity',
    requiredSkills: ['Cybersecurity Fundamentals', 'System Design', 'Python', 'Problem Solving'],
    minimumCGPA: 7.5,
    eligibleBranches: ['Computer Science and Engineering', 'Information Technology', 'Cybersecurity'],
    description: 'Conduct security vulnerability audits, implement threat intelligence detection tools, and safeguard infrastructure against modern attack vectors.',
    responsibilities: [
      'Monitor SIEM dashboard logs for security anomalies.',
      'Perform ethical penetration testing on staging Web applications.',
      'Document incident response reports and mitigation steps.'
    ],
    perks: ['Security Clearance Sponsorship', 'Quarterly Rewards', 'Gym Membership']
  },
  {
    id: 'opp-6',
    title: 'Backend Software Engineer (FastAPI / Python)',
    company: 'DataStream Technologies',
    companyLogo: '⚙️',
    location: 'Bengaluru, KA (Onsite)',
    type: 'Full-time',
    stipend: '₹14.0 LPA',
    duration: 'Full-time Role',
    deadline: '2026-11-01',
    domain: 'Backend Development',
    requiredSkills: ['Python', 'FastAPI', 'PostgreSQL', 'Docker', 'System Design', 'REST APIs'],
    minimumCGPA: 8.0,
    eligibleBranches: ['Computer Science and Engineering', 'Information Technology'],
    description: 'Design high-concurrency microservices, optimize SQL queries, and implement asynchronous event handling for financial data platforms.',
    responsibilities: [
      'Build scalable RESTful API endpoints with FastAPI and Pydantic.',
      'Optimize database queries with PostgreSQL indexing.',
      'Write comprehensive integration unit tests.'
    ],
    perks: ['Relocation Allowance', 'Stock Options (ESOPs)', 'Free Meals']
  },
  {
    id: 'opp-7',
    title: 'UI/UX Product Designer Intern',
    company: 'PixelCraft Studio',
    companyLogo: '🎨',
    location: 'Remote',
    type: 'Remote Internship',
    stipend: '₹25,000 / month',
    duration: '3 Months',
    deadline: '2026-09-28',
    domain: 'Design & User Experience',
    requiredSkills: ['Figma / UI Design', 'Technical Communication', 'Presentation Skills', 'Adaptability'],
    minimumCGPA: 6.5,
    eligibleBranches: ['All Engineering Branches', 'Design / Media'],
    description: 'Craft beautiful SaaS user journeys, design wireframes, high-fidelity prototypes, and design systems for web and mobile products.',
    responsibilities: [
      'Conduct user experience research and usability interviews.',
      'Design interactive UI prototypes in Figma.',
      'Maintain design token component libraries for engineering handoff.'
    ],
    perks: ['Remote Flexibility', 'Design Book Stipend', 'Recommendation Letter']
  },
  {
    id: 'opp-8',
    title: 'Generative AI Applications Intern',
    company: 'Aura Intelligence',
    companyLogo: '🧠',
    location: 'Noida, UP (Hybrid)',
    type: 'Internship',
    stipend: '₹50,000 / month',
    duration: '6 Months',
    deadline: '2026-10-12',
    domain: 'Artificial Intelligence',
    requiredSkills: ['Prompt Engineering & LLMs', 'Python', 'Natural Language Processing (NLP)', 'REST APIs'],
    minimumCGPA: 8.2,
    eligibleBranches: ['Computer Science and Engineering', 'AI & Data Science', 'Information Technology'],
    description: 'Build RAG (Retrieval-Augmented Generation) applications, fine-tune open-weight models like Llama 3, and deploy AI copilots.',
    responsibilities: [
      'Build vector database indexing pipelines using LangChain / LlamaIndex.',
      'Design prompt engineering templates for specialized domain agents.',
      'Evaluate model hallucination rates and safety guardrails.'
    ],
    perks: ['Top-tier Stipend', 'High PPO Conversion Rate', 'Publication Assistance']
  },
  {
    id: 'opp-9',
    title: 'Embedded Systems & IoT Engineer Intern',
    company: 'RoboTech Solutions',
    companyLogo: '🤖',
    location: 'Chennai, TN (Onsite)',
    type: 'Internship',
    stipend: '₹28,000 / month',
    duration: '6 Months',
    deadline: '2026-10-18',
    domain: 'Hardware & Systems',
    requiredSkills: ['Python', 'Problem Solving', 'Critical Thinking', 'Team Collaboration'],
    minimumCGPA: 7.2,
    eligibleBranches: ['Electronics & Comm', 'Electrical', 'Robotics'],
    description: 'Develop firmware, sensor integration protocols, and micro-controller software for smart industrial automation units.',
    responsibilities: [
      'Program ARM Cortex microcontrollers in C/C++ and Python.',
      'Test IoT wireless communication protocols (MQTT, BLE).',
      'Debug hardware schematics and PCB mockups.'
    ],
    perks: ['Hardware Lab Access', 'Patent Co-Authorship', 'Certificate']
  },
  {
    id: 'opp-10',
    title: 'Product Management Intern',
    company: 'InnoVenture Labs',
    companyLogo: '💡',
    location: 'Bengaluru, KA (Hybrid)',
    type: 'Internship',
    stipend: '₹35,000 / month',
    duration: '4 Months',
    deadline: '2026-10-08',
    domain: 'Product & Strategy',
    requiredSkills: ['Problem Solving', 'Technical Communication', 'Data Visualization (PowerBI / Tableau)', 'Critical Thinking'],
    minimumCGPA: 7.8,
    eligibleBranches: ['All Engineering Branches', 'MBA / Management'],
    description: 'Bridge tech developers and enterprise customers by defining feature specs, analyzing user churn metrics, and maintaining product roadmaps.',
    responsibilities: [
      'Write detailed PRDs (Product Requirement Documents).',
      'Analyze competitor feature benchmarks.',
      'Run weekly sprint review meetings with engineering leads.'
    ],
    perks: ['Executive Mentorship', 'Product Management Certificate', 'PPO Track']
  },
  {
    id: 'opp-11',
    title: 'Data Engineer Intern',
    company: 'FinTech Insights',
    companyLogo: '🏦',
    location: 'Mumbai, MH (Hybrid)',
    type: 'Internship',
    stipend: '₹40,000 / month',
    duration: '6 Months',
    deadline: '2026-10-25',
    domain: 'Data Engineering',
    requiredSkills: ['SQL', 'Python', 'PostgreSQL', 'Docker', 'REST APIs'],
    minimumCGPA: 8.0,
    eligibleBranches: ['Computer Science and Engineering', 'Information Technology', 'Data Science'],
    description: 'Construct fault-tolerant streaming ETL pipelines processing millions of daily financial transactions.',
    responsibilities: [
      'Design Apache Airflow DAGs for batch data jobs.',
      'Optimize database indexing and data warehousing schemas.',
      'Ensure data quality and automated test coverage.'
    ],
    perks: ['Subsidized Housing', 'Financial Tech Certification', 'PPO Offer']
  },
  {
    id: 'opp-12',
    title: 'Mobile App Developer (React Native)',
    company: 'MobilityX',
    companyLogo: '📱',
    location: 'Remote',
    type: 'Remote Internship',
    stipend: '₹32,000 / month',
    duration: '4 Months',
    deadline: '2026-10-02',
    domain: 'Mobile Development',
    requiredSkills: ['React.js', 'TypeScript', 'REST APIs', 'Git & GitHub'],
    minimumCGPA: 7.0,
    eligibleBranches: ['Computer Science and Engineering', 'Information Technology'],
    description: 'Build cross-platform iOS and Android consumer mobile applications using React Native and Expo.',
    responsibilities: [
      'Build performant mobile UI screens with native animations.',
      'Integrate offline caching and push notifications.',
      'Submit app builds to Apple App Store & Google Play Console.'
    ],
    perks: ['Remote Work', 'Device Allowance', 'Certificate']
  },
  {
    id: 'opp-13',
    title: 'System Architect Associate',
    company: 'CoreInfra Labs',
    companyLogo: '🏛️',
    location: 'Bengaluru, KA (Onsite)',
    type: 'Full-time',
    stipend: '₹16.0 LPA',
    duration: 'Full-time Role',
    deadline: '2026-11-15',
    domain: 'System Architecture',
    requiredSkills: ['System Design', 'Data Structures & Algorithms', 'C++', 'Python', 'Linux & Networking'],
    minimumCGPA: 8.5,
    eligibleBranches: ['Computer Science and Engineering'],
    description: 'Design low-latency distributed systems, memory managers, and high-performance server backbones.',
    responsibilities: [
      'Architect distributed fault-tolerant microservices.',
      'Optimize memory allocation and network socket IO performance.',
      'Write architectural decision records (ADRs).'
    ],
    perks: ['Signing Bonus ₹1.5L', 'Comprehensive Health Plan', 'ESOPs']
  },
  {
    id: 'opp-14',
    title: 'QA & Test Automation Specialist',
    company: 'QualityFirst Tech',
    companyLogo: '🧪',
    location: 'Remote',
    type: 'Remote Internship',
    stipend: '₹22,000 / month',
    duration: '3 Months',
    deadline: '2026-09-25',
    domain: 'Software Testing',
    requiredSkills: ['Python', 'REST APIs', 'Git & GitHub', 'Problem Solving'],
    minimumCGPA: 6.8,
    eligibleBranches: ['All Engineering Branches'],
    description: 'Write end-to-end automated testing scripts using Cypress and Playwright to guarantee software reliability.',
    responsibilities: [
      'Create automated API test suites using PyTest.',
      'Execute load testing and report bug tracebacks in Jira.',
      'Maintain continuous regression test pipeline execution.'
    ],
    perks: ['Flexible Work Schedule', 'Software Testing Cert', 'PPO Track']
  },
  {
    id: 'opp-15',
    title: 'Computer Vision Research Intern',
    company: 'VisionEdge AI',
    companyLogo: '👁️',
    location: 'Hyderabad, TS (Onsite)',
    type: 'Internship',
    stipend: '₹42,000 / month',
    duration: '6 Months',
    deadline: '2026-10-30',
    domain: 'Artificial Intelligence',
    requiredSkills: ['Python', 'TensorFlow', 'Deep Learning', 'Pandas & NumPy'],
    minimumCGPA: 8.2,
    eligibleBranches: ['Computer Science and Engineering', 'AI & Data Science'],
    description: 'Develop object detection and video analytics models for autonomous vehicle edge hardware.',
    responsibilities: [
      'Train YOLOv8 & OpenCV image processing pipelines.',
      'Quantize deep neural networks for edge TPU deployment.',
      'Benchmark FPS and latency on embedded Nvidia Jetson hardware.'
    ],
    perks: ['GPU Cluster Access', 'Research Paper Authorship', 'PPO Track']
  }
];
